name: Showwcase Profile Card
on:
  schedule:
    # Runs every day at 12:00
    - cron: "0 12 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SHOWWCASE_API_KEY: ${{ secrets.SHOWWCASE_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: sahil-sagwekar2652/github-readme-showwcase-cards@main
        id: showwcase-cards
        with: 
          api_key: "9dd5899c1b71c7aad37c207bc781d86674db487ac4675b034e"
          theme: "dark"
          username: "sahil-sagwekar2652"
